import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white text-gray-900">
        <header className="border-b">
          <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
            <a href="/" className="text-lg font-semibold tracking-tight">
              IDHub
            </a>

            <nav className="flex gap-6 text-sm font-medium text-gray-700">
              <a href="/blog" className="hover:text-gray-900">Blog</a>
              <a href="/cases" className="hover:text-gray-900">Cases</a>
              <a href="/mechid" className="hover:text-gray-900">MechID</a>
              <a href="/about" className="hover:text-gray-900">About</a>
            </nav>
          </div>
        </header>

        <div className="mx-auto max-w-5xl px-6">
          {children}
        </div>
      </body>

    </html>
  );
}
