/**
 * Antimicrobial spectrum reference data.
 *
 * S = Usually susceptible
 * I = Variable / intermediate
 * R = Intrinsically resistant or usually resistant
 * — = Not applicable / not tested
 *
 * This is an educational simplification. Real susceptibility depends on
 * local antibiograms and CLSI/EUCAST breakpoints.
 */

export type Susceptibility = "S" | "I" | "R" | "—";

export type OrganismSpectrum = {
  organism: string;
  gramStain: "Gram-positive" | "Gram-negative" | "Anaerobe" | "Atypical" | "Fungal" | "Mycobacterial";
  antibiotics: Record<string, Susceptibility>;
};

// Antibiotics in display order (columns)
export const ANTIBIOTICS = [
  "Ampicillin",
  "Amoxicillin-clavulanate",
  "Piperacillin-tazobactam",
  "Ceftriaxone",
  "Cefepime",
  "Meropenem",
  "Aztreonam",
  "Ciprofloxacin",
  "Levofloxacin",
  "TMP-SMX",
  "Doxycycline",
  "Vancomycin",
  "Linezolid",
  "Daptomycin",
  "Metronidazole",
] as const;

export type AntibioticName = (typeof ANTIBIOTICS)[number];

export const ORGANISMS: OrganismSpectrum[] = [
  // ─── Gram-positive cocci ───
  {
    organism: "Staphylococcus aureus (MSSA)",
    gramStain: "Gram-positive",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "S",
      "Piperacillin-tazobactam": "S",
      "Ceftriaxone": "S",
      "Cefepime": "S",
      "Meropenem": "S",
      "Aztreonam": "R",
      "Ciprofloxacin": "S",
      "Levofloxacin": "S",
      "TMP-SMX": "S",
      "Doxycycline": "S",
      "Vancomycin": "S",
      "Linezolid": "S",
      "Daptomycin": "S",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Staphylococcus aureus (MRSA)",
    gramStain: "Gram-positive",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "R",
      "Piperacillin-tazobactam": "R",
      "Ceftriaxone": "R",
      "Cefepime": "R",
      "Meropenem": "R",
      "Aztreonam": "R",
      "Ciprofloxacin": "I",
      "Levofloxacin": "I",
      "TMP-SMX": "S",
      "Doxycycline": "S",
      "Vancomycin": "S",
      "Linezolid": "S",
      "Daptomycin": "S",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Streptococcus pneumoniae",
    gramStain: "Gram-positive",
    antibiotics: {
      "Ampicillin": "S",
      "Amoxicillin-clavulanate": "S",
      "Piperacillin-tazobactam": "S",
      "Ceftriaxone": "S",
      "Cefepime": "S",
      "Meropenem": "S",
      "Aztreonam": "R",
      "Ciprofloxacin": "R",
      "Levofloxacin": "S",
      "TMP-SMX": "I",
      "Doxycycline": "I",
      "Vancomycin": "S",
      "Linezolid": "S",
      "Daptomycin": "S",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Streptococcus pyogenes (GAS)",
    gramStain: "Gram-positive",
    antibiotics: {
      "Ampicillin": "S",
      "Amoxicillin-clavulanate": "S",
      "Piperacillin-tazobactam": "S",
      "Ceftriaxone": "S",
      "Cefepime": "S",
      "Meropenem": "S",
      "Aztreonam": "R",
      "Ciprofloxacin": "R",
      "Levofloxacin": "I",
      "TMP-SMX": "R",
      "Doxycycline": "I",
      "Vancomycin": "S",
      "Linezolid": "S",
      "Daptomycin": "S",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Streptococcus agalactiae (GBS)",
    gramStain: "Gram-positive",
    antibiotics: {
      "Ampicillin": "S",
      "Amoxicillin-clavulanate": "S",
      "Piperacillin-tazobactam": "S",
      "Ceftriaxone": "S",
      "Cefepime": "S",
      "Meropenem": "S",
      "Aztreonam": "R",
      "Ciprofloxacin": "R",
      "Levofloxacin": "I",
      "TMP-SMX": "R",
      "Doxycycline": "I",
      "Vancomycin": "S",
      "Linezolid": "S",
      "Daptomycin": "S",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Enterococcus faecalis",
    gramStain: "Gram-positive",
    antibiotics: {
      "Ampicillin": "S",
      "Amoxicillin-clavulanate": "S",
      "Piperacillin-tazobactam": "S",
      "Ceftriaxone": "R",
      "Cefepime": "R",
      "Meropenem": "R",
      "Aztreonam": "R",
      "Ciprofloxacin": "I",
      "Levofloxacin": "I",
      "TMP-SMX": "R",
      "Doxycycline": "I",
      "Vancomycin": "S",
      "Linezolid": "S",
      "Daptomycin": "S",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Enterococcus faecium",
    gramStain: "Gram-positive",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "R",
      "Piperacillin-tazobactam": "R",
      "Ceftriaxone": "R",
      "Cefepime": "R",
      "Meropenem": "R",
      "Aztreonam": "R",
      "Ciprofloxacin": "R",
      "Levofloxacin": "R",
      "TMP-SMX": "R",
      "Doxycycline": "I",
      "Vancomycin": "I",
      "Linezolid": "S",
      "Daptomycin": "S",
      "Metronidazole": "R",
    },
  },
  // ─── Gram-negative rods ───
  {
    organism: "Escherichia coli",
    gramStain: "Gram-negative",
    antibiotics: {
      "Ampicillin": "I",
      "Amoxicillin-clavulanate": "S",
      "Piperacillin-tazobactam": "S",
      "Ceftriaxone": "S",
      "Cefepime": "S",
      "Meropenem": "S",
      "Aztreonam": "S",
      "Ciprofloxacin": "I",
      "Levofloxacin": "I",
      "TMP-SMX": "I",
      "Doxycycline": "I",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Klebsiella pneumoniae",
    gramStain: "Gram-negative",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "S",
      "Piperacillin-tazobactam": "S",
      "Ceftriaxone": "S",
      "Cefepime": "S",
      "Meropenem": "S",
      "Aztreonam": "S",
      "Ciprofloxacin": "S",
      "Levofloxacin": "S",
      "TMP-SMX": "S",
      "Doxycycline": "I",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Proteus mirabilis",
    gramStain: "Gram-negative",
    antibiotics: {
      "Ampicillin": "S",
      "Amoxicillin-clavulanate": "S",
      "Piperacillin-tazobactam": "S",
      "Ceftriaxone": "S",
      "Cefepime": "S",
      "Meropenem": "S",
      "Aztreonam": "S",
      "Ciprofloxacin": "S",
      "Levofloxacin": "S",
      "TMP-SMX": "S",
      "Doxycycline": "R",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Pseudomonas aeruginosa",
    gramStain: "Gram-negative",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "R",
      "Piperacillin-tazobactam": "S",
      "Ceftriaxone": "R",
      "Cefepime": "S",
      "Meropenem": "S",
      "Aztreonam": "S",
      "Ciprofloxacin": "S",
      "Levofloxacin": "S",
      "TMP-SMX": "R",
      "Doxycycline": "R",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Acinetobacter baumannii",
    gramStain: "Gram-negative",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "R",
      "Piperacillin-tazobactam": "I",
      "Ceftriaxone": "R",
      "Cefepime": "I",
      "Meropenem": "I",
      "Aztreonam": "R",
      "Ciprofloxacin": "I",
      "Levofloxacin": "I",
      "TMP-SMX": "I",
      "Doxycycline": "I",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Stenotrophomonas maltophilia",
    gramStain: "Gram-negative",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "R",
      "Piperacillin-tazobactam": "R",
      "Ceftriaxone": "R",
      "Cefepime": "R",
      "Meropenem": "R",
      "Aztreonam": "R",
      "Ciprofloxacin": "I",
      "Levofloxacin": "S",
      "TMP-SMX": "S",
      "Doxycycline": "S",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Serratia marcescens",
    gramStain: "Gram-negative",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "R",
      "Piperacillin-tazobactam": "S",
      "Ceftriaxone": "S",
      "Cefepime": "S",
      "Meropenem": "S",
      "Aztreonam": "S",
      "Ciprofloxacin": "S",
      "Levofloxacin": "S",
      "TMP-SMX": "S",
      "Doxycycline": "I",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Enterobacter cloacae",
    gramStain: "Gram-negative",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "R",
      "Piperacillin-tazobactam": "I",
      "Ceftriaxone": "I",
      "Cefepime": "S",
      "Meropenem": "S",
      "Aztreonam": "I",
      "Ciprofloxacin": "S",
      "Levofloxacin": "S",
      "TMP-SMX": "S",
      "Doxycycline": "I",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Citrobacter freundii",
    gramStain: "Gram-negative",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "R",
      "Piperacillin-tazobactam": "I",
      "Ceftriaxone": "I",
      "Cefepime": "S",
      "Meropenem": "S",
      "Aztreonam": "I",
      "Ciprofloxacin": "S",
      "Levofloxacin": "S",
      "TMP-SMX": "S",
      "Doxycycline": "I",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Haemophilus influenzae",
    gramStain: "Gram-negative",
    antibiotics: {
      "Ampicillin": "I",
      "Amoxicillin-clavulanate": "S",
      "Piperacillin-tazobactam": "S",
      "Ceftriaxone": "S",
      "Cefepime": "S",
      "Meropenem": "S",
      "Aztreonam": "S",
      "Ciprofloxacin": "S",
      "Levofloxacin": "S",
      "TMP-SMX": "I",
      "Doxycycline": "I",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Neisseria meningitidis",
    gramStain: "Gram-negative",
    antibiotics: {
      "Ampicillin": "S",
      "Amoxicillin-clavulanate": "S",
      "Piperacillin-tazobactam": "S",
      "Ceftriaxone": "S",
      "Cefepime": "S",
      "Meropenem": "S",
      "Aztreonam": "S",
      "Ciprofloxacin": "S",
      "Levofloxacin": "S",
      "TMP-SMX": "I",
      "Doxycycline": "I",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
  // ─── Anaerobes ───
  {
    organism: "Bacteroides fragilis",
    gramStain: "Anaerobe",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "S",
      "Piperacillin-tazobactam": "S",
      "Ceftriaxone": "R",
      "Cefepime": "R",
      "Meropenem": "S",
      "Aztreonam": "R",
      "Ciprofloxacin": "R",
      "Levofloxacin": "R",
      "TMP-SMX": "R",
      "Doxycycline": "R",
      "Vancomycin": "R",
      "Linezolid": "I",
      "Daptomycin": "R",
      "Metronidazole": "S",
    },
  },
  {
    organism: "Clostridioides difficile",
    gramStain: "Anaerobe",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "R",
      "Piperacillin-tazobactam": "R",
      "Ceftriaxone": "R",
      "Cefepime": "R",
      "Meropenem": "R",
      "Aztreonam": "R",
      "Ciprofloxacin": "R",
      "Levofloxacin": "R",
      "TMP-SMX": "R",
      "Doxycycline": "R",
      "Vancomycin": "S",
      "Linezolid": "—",
      "Daptomycin": "—",
      "Metronidazole": "S",
    },
  },
  // ─── Atypicals ───
  {
    organism: "Mycoplasma pneumoniae",
    gramStain: "Atypical",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "R",
      "Piperacillin-tazobactam": "R",
      "Ceftriaxone": "R",
      "Cefepime": "R",
      "Meropenem": "R",
      "Aztreonam": "R",
      "Ciprofloxacin": "S",
      "Levofloxacin": "S",
      "TMP-SMX": "R",
      "Doxycycline": "S",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Legionella pneumophila",
    gramStain: "Atypical",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "R",
      "Piperacillin-tazobactam": "R",
      "Ceftriaxone": "R",
      "Cefepime": "R",
      "Meropenem": "R",
      "Aztreonam": "R",
      "Ciprofloxacin": "S",
      "Levofloxacin": "S",
      "TMP-SMX": "R",
      "Doxycycline": "S",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
  {
    organism: "Chlamydophila pneumoniae",
    gramStain: "Atypical",
    antibiotics: {
      "Ampicillin": "R",
      "Amoxicillin-clavulanate": "R",
      "Piperacillin-tazobactam": "R",
      "Ceftriaxone": "R",
      "Cefepime": "R",
      "Meropenem": "R",
      "Aztreonam": "R",
      "Ciprofloxacin": "S",
      "Levofloxacin": "S",
      "TMP-SMX": "R",
      "Doxycycline": "S",
      "Vancomycin": "R",
      "Linezolid": "R",
      "Daptomycin": "R",
      "Metronidazole": "R",
    },
  },
];
