/**
 * Antibacterial spectrum reference data.
 *
 * This tool separates expected in vitro activity from clinical preference.
 * Real decisions still require syndrome, source control, severity, patient factors,
 * susceptibility testing, local antibiograms, and institutional guidance.
 */

export type SpectrumActivity = "preferred" | "active" | "variable" | "inactive" | "avoid" | "site-only";

export type SpectrumCell = {
  activity: SpectrumActivity;
  note?: string;
  requiresSusceptibility?: boolean;
  siteCaveat?: string;
  resistanceCaveat?: string;
};

export type Antibiotic = {
  name: string;
  className: string;
  route: "IV" | "PO" | "IV/PO" | "PO/local";
  aliases: string[];
  note?: string;
};

export const ANTIBIOTICS = [
  { name: "Penicillin G", className: "Penicillins", route: "IV", aliases: ["pen g", "benzylpenicillin"] },
  { name: "Ampicillin", className: "Penicillins", route: "IV/PO", aliases: ["amox", "amoxicillin"] },
  { name: "Nafcillin/Oxacillin", className: "Anti-staph beta-lactams", route: "IV", aliases: ["nafcillin", "oxacillin"] },
  { name: "Cefazolin", className: "Anti-staph beta-lactams", route: "IV", aliases: ["ancef"] },
  { name: "Cephalexin", className: "Oral cephalosporins", route: "PO", aliases: ["keflex"] },
  { name: "Amox-clav", className: "BL/BLI", route: "PO", aliases: ["augmentin", "amoxicillin clavulanate"] },
  { name: "Amp-sulbactam", className: "BL/BLI", route: "IV", aliases: ["unasyn", "ampicillin sulbactam"] },
  { name: "Pip-tazo", className: "BL/BLI", route: "IV", aliases: ["zosyn", "piperacillin tazobactam"] },
  { name: "Ceftriaxone", className: "Cephalosporins", route: "IV", aliases: ["ctx", "rocephin"] },
  { name: "Ceftazidime", className: "Cephalosporins", route: "IV", aliases: ["fortaz"] },
  { name: "Cefepime", className: "Cephalosporins", route: "IV", aliases: ["maxipime"] },
  { name: "Ceftaroline", className: "Cephalosporins", route: "IV", aliases: ["teflaro"] },
  { name: "Ertapenem", className: "Carbapenems", route: "IV", aliases: ["invanz"] },
  { name: "Meropenem", className: "Carbapenems", route: "IV", aliases: ["mero", "merrem"] },
  { name: "Aztreonam", className: "Monobactam", route: "IV", aliases: ["azactam"] },
  { name: "Ceftaz-avibactam", className: "Novel gram-negative", route: "IV", aliases: ["avycaz", "ceftazidime avibactam"] },
  { name: "Ceftolo-tazo", className: "Novel gram-negative", route: "IV", aliases: ["zerbaxa", "ceftolozane tazobactam"] },
  { name: "Cefiderocol", className: "Novel gram-negative", route: "IV", aliases: ["fetroja"] },
  { name: "Vancomycin IV", className: "Gram-positive", route: "IV", aliases: ["vanco iv", "iv vancomycin"] },
  { name: "Vancomycin PO", className: "CDI", route: "PO/local", aliases: ["vanco po", "oral vancomycin"] },
  { name: "Fidaxomicin", className: "CDI", route: "PO/local", aliases: ["dificid"] },
  { name: "Daptomycin", className: "Gram-positive", route: "IV", aliases: ["dapto", "cubicin"], note: "Do not use for pneumonia." },
  { name: "Linezolid", className: "Gram-positive", route: "IV/PO", aliases: ["zyvox"] },
  { name: "Clindamycin", className: "Protein synthesis", route: "IV/PO", aliases: ["clinda"] },
  { name: "Azithromycin", className: "Macrolides", route: "IV/PO", aliases: ["azithro", "z-pak"] },
  { name: "Doxycycline", className: "Tetracyclines", route: "IV/PO", aliases: ["doxy"] },
  { name: "Minocycline", className: "Tetracyclines", route: "IV/PO", aliases: ["mino"] },
  { name: "Tigecycline/Eravacycline", className: "Tetracyclines", route: "IV", aliases: ["tigecycline", "eravacycline", "tygacil", "xerava"] },
  { name: "TMP-SMX", className: "Folate pathway", route: "IV/PO", aliases: ["bactrim", "trimethoprim sulfamethoxazole", "smx"] },
  { name: "Ciprofloxacin", className: "Fluoroquinolones", route: "IV/PO", aliases: ["cipro"] },
  { name: "Levofloxacin", className: "Fluoroquinolones", route: "IV/PO", aliases: ["levo", "levaquin"] },
  { name: "Metronidazole", className: "Anaerobe", route: "IV/PO", aliases: ["flagyl"] },
  { name: "Nitrofurantoin", className: "Urine-only", route: "PO/local", aliases: ["macrobid"] },
  { name: "Fosfomycin PO", className: "Urine-only", route: "PO/local", aliases: ["fosfomycin", "monurol"] },
  { name: "Gent/Tobra", className: "Aminoglycosides", route: "IV", aliases: ["gentamicin", "tobramycin", "gent", "tobra"] },
  { name: "Amikacin", className: "Aminoglycosides", route: "IV", aliases: ["amikin"] },
] as const satisfies readonly Antibiotic[];

export type AntibioticName = (typeof ANTIBIOTICS)[number]["name"];

export type OrganismCategory =
  | "Gram-positive cocci"
  | "Gram-positive rods"
  | "Enterobacterales"
  | "Non-fermenters"
  | "Respiratory / GN diplococci"
  | "GI / water / zoonotic"
  | "Anaerobes"
  | "Atypical / intracellular";

export type OrganismSpectrum = {
  organism: string;
  category: OrganismCategory;
  aliases: string[];
  summary: string;
  keyCaveats: string[];
  antibiotics: Partial<Record<AntibioticName, SpectrumCell>>;
};

const p = (note?: string): SpectrumCell => ({ activity: "preferred", note });
const a = (note?: string): SpectrumCell => ({ activity: "active", note });
const v = (note?: string): SpectrumCell => ({ activity: "variable", note, requiresSusceptibility: true });
const r = (note?: string): SpectrumCell => ({ activity: "inactive", note });
const avoid = (note: string): SpectrumCell => ({ activity: "avoid", note });
const site = (note: string): SpectrumCell => ({ activity: "site-only", note, siteCaveat: note });

export const DEFAULT_CELL: SpectrumCell = { activity: "inactive" };

export const ACTIVITY_LABELS: Record<SpectrumActivity, string> = {
  preferred: "Preferred",
  active: "Active",
  variable: "Variable / test",
  inactive: "Inactive",
  avoid: "Avoid / unreliable",
  "site-only": "Site-only",
};

export const ORGANISMS: OrganismSpectrum[] = [
  {
    organism: "Staphylococcus aureus (MSSA)",
    category: "Gram-positive cocci",
    aliases: ["mssa", "staph aureus", "s aureus"],
    summary: "Methicillin-susceptible S. aureus is best treated with anti-staphylococcal beta-lactams when feasible.",
    keyCaveats: ["Vancomycin is active but inferior to beta-lactams for serious MSSA infection.", "Ceftriaxone may be convenient but is not preferred for serious bacteremia/endocarditis."],
    antibiotics: {
      "Nafcillin/Oxacillin": p("Preferred for serious MSSA infections when tolerated."),
      Cefazolin: p("Preferred for many serious MSSA infections."),
      Cephalexin: p("Oral option for mild susceptible skin/soft tissue infection."),
      "Amox-clav": a(),
      "Amp-sulbactam": a(),
      "Pip-tazo": a("Active but unnecessarily broad for definitive MSSA therapy."),
      Ceftriaxone: a("May be active; not preferred for serious MSSA bacteremia/endocarditis."),
      Cefepime: a("Active but broad and not preferred for definitive therapy."),
      Meropenem: a("Active but unnecessarily broad."),
      Ceftaroline: a("Active against MSSA and MRSA."),
      "Vancomycin IV": a("Use when beta-lactams cannot be used or MRSA not excluded."),
      Daptomycin: a("Not for pneumonia."),
      Linezolid: a(),
      Clindamycin: v("Use only if susceptible; inducible resistance may matter."),
      Doxycycline: v(),
      "TMP-SMX": v(),
      Ciprofloxacin: v("Resistance emerges; not a preferred anti-staphylococcal agent."),
      Levofloxacin: v("Resistance emerges; not a preferred anti-staphylococcal agent."),
    },
  },
  {
    organism: "Staphylococcus aureus (MRSA)",
    category: "Gram-positive cocci",
    aliases: ["mrsa", "methicillin resistant staph aureus"],
    summary: "MRSA is resistant to routine beta-lactams; use MRSA-active agents and interpret oral options by syndrome and susceptibility.",
    keyCaveats: ["Ceftaroline is the major beta-lactam exception.", "Daptomycin is not used for pneumonia."],
    antibiotics: {
      Ceftaroline: a("MRSA-active cephalosporin."),
      "Vancomycin IV": p("Standard IV therapy for many serious MRSA infections."),
      Daptomycin: p("Preferred alternative for bacteremia/right-sided endocarditis; not pneumonia."),
      Linezolid: p("Useful for MRSA pneumonia and oral step-down in selected cases."),
      Clindamycin: v("Only if susceptible and D-test negative when relevant."),
      Doxycycline: v("Often used for mild SSTI if susceptible; not for bacteremia."),
      "TMP-SMX": v("Often used for mild SSTI if susceptible; not preferred for bacteremia."),
      Minocycline: v(),
    },
  },
  {
    organism: "Streptococcus pyogenes (GAS)",
    category: "Gram-positive cocci",
    aliases: ["gas", "group a strep", "s pyogenes"],
    summary: "Group A Streptococcus remains predictably beta-lactam susceptible.",
    keyCaveats: ["Add clindamycin for toxin suppression in necrotizing fasciitis or streptococcal toxic shock."],
    antibiotics: {
      "Penicillin G": p("Drug of choice when narrow therapy is appropriate."),
      Ampicillin: p(),
      Cefazolin: p(),
      Cephalexin: p(),
      Ceftriaxone: a(),
      "Vancomycin IV": a("Active but broader than needed if beta-lactams tolerated."),
      Linezolid: a(),
      Clindamycin: a("Use with beta-lactam for toxin suppression in severe toxin-mediated disease."),
      Azithromycin: v("Macrolide resistance varies."),
      Doxycycline: avoid("Not reliable for GAS."),
      "TMP-SMX": avoid("Not reliable for GAS."),
    },
  },
  {
    organism: "Streptococcus pneumoniae",
    category: "Gram-positive cocci",
    aliases: ["pneumococcus", "s pneumo", "strep pneumo"],
    summary: "Therapy depends heavily on syndrome, breakpoints, and resistance phenotype.",
    keyCaveats: ["Meningitis breakpoints differ from non-meningitis breakpoints.", "Daptomycin is not used for pneumonia."],
    antibiotics: {
      "Penicillin G": v("Susceptibility and syndrome dependent."),
      Ampicillin: v("Susceptibility and syndrome dependent."),
      Ceftriaxone: p("Common preferred agent for invasive susceptible disease; meningitis requires specific breakpoints."),
      Cefepime: a(),
      Ceftaroline: a(),
      Levofloxacin: a("Respiratory fluoroquinolone option."),
      "Vancomycin IV": a("Used with ceftriaxone empirically for meningitis until susceptibilities return."),
      Linezolid: a(),
      Azithromycin: v("Macrolide resistance is common in many regions."),
      Doxycycline: v(),
      "TMP-SMX": v(),
      Daptomycin: avoid("Not for pneumonia."),
    },
  },
  {
    organism: "Enterococcus faecalis",
    category: "Gram-positive cocci",
    aliases: ["e faecalis", "enterococcus"],
    summary: "E. faecalis is often ampicillin susceptible; cephalosporins are intrinsically inactive.",
    keyCaveats: ["Cephalosporins do not treat Enterococcus.", "Bactericidal synergy may be needed for endocarditis."],
    antibiotics: {
      Ampicillin: p("Preferred when susceptible."),
      "Amp-sulbactam": p(),
      "Pip-tazo": a(),
      "Vancomycin IV": a("Use for susceptible isolates when beta-lactams cannot be used."),
      Daptomycin: a(),
      Linezolid: a(),
      Nitrofurantoin: site("Cystitis only if susceptible."),
      "Fosfomycin PO": site("Cystitis only; verify susceptibility if available."),
      Ceftriaxone: r("Cephalosporins are intrinsically inactive."),
      Cefepime: r("Cephalosporins are intrinsically inactive."),
      "TMP-SMX": avoid("Not reliable clinically despite possible in vitro appearance."),
    },
  },
  {
    organism: "Enterococcus faecium / VRE",
    category: "Gram-positive cocci",
    aliases: ["e faecium", "vre", "vancomycin resistant enterococcus"],
    summary: "E. faecium is frequently ampicillin resistant and may be vancomycin resistant.",
    keyCaveats: ["Use species and susceptibility data; E. faecium assumptions differ from E. faecalis.", "Cephalosporins are intrinsically inactive."],
    antibiotics: {
      Ampicillin: v("Some isolates susceptible, but many E. faecium are resistant."),
      "Vancomycin IV": v("Inactive for VRE; active only if vancomycin susceptible."),
      Daptomycin: p("Common preferred option for VRE bacteremia; dose matters."),
      Linezolid: p("Useful for VRE, including pneumonia when true infection."),
      "Tigecycline/Eravacycline": a("Not for bacteremia."),
      Nitrofurantoin: site("Cystitis only if susceptible."),
      Ceftriaxone: r("Cephalosporins are intrinsically inactive."),
      Cefepime: r("Cephalosporins are intrinsically inactive."),
    },
  },
  {
    organism: "Listeria monocytogenes",
    category: "Gram-positive rods",
    aliases: ["listeria"],
    summary: "Listeria is intrinsically resistant to cephalosporins; ampicillin is the classic therapy.",
    keyCaveats: ["Cephalosporin-based meningitis regimens miss Listeria."],
    antibiotics: {
      Ampicillin: p("Preferred backbone therapy."),
      "Penicillin G": a(),
      Meropenem: a(),
      "TMP-SMX": a("Alternative in severe beta-lactam allergy."),
      "Gent/Tobra": a("Sometimes used for synergy."),
      Ceftriaxone: r("Cephalosporins do not cover Listeria."),
      Cefepime: r("Cephalosporins do not cover Listeria."),
    },
  },
  {
    organism: "Escherichia coli / susceptible Enterobacterales",
    category: "Enterobacterales",
    aliases: ["e coli", "enterobacterales", "susceptible e coli"],
    summary: "Susceptibility is increasingly local and isolate-specific; separate resistant phenotypes matter.",
    keyCaveats: ["Do not assume fluoroquinolone or TMP-SMX susceptibility empirically.", "Nitrofurantoin and fosfomycin are cystitis-only."],
    antibiotics: {
      Ceftriaxone: p("Common preferred IV option when susceptible."),
      Cefepime: a(),
      "Pip-tazo": a(),
      Ertapenem: a("Active but broad; reserve when narrower options unsuitable."),
      Meropenem: a("Active but broad."),
      Aztreonam: a("If susceptible; no gram-positive or anaerobe coverage."),
      "Amox-clav": v(),
      "Amp-sulbactam": v(),
      Ampicillin: v("Often resistant."),
      Ciprofloxacin: v(),
      Levofloxacin: v(),
      "TMP-SMX": v(),
      "Gent/Tobra": v(),
      Amikacin: v(),
      Nitrofurantoin: site("Uncomplicated cystitis only."),
      "Fosfomycin PO": site("Uncomplicated cystitis, strongest for E. coli."),
    },
  },
  {
    organism: "Klebsiella pneumoniae / Klebsiella oxytoca",
    category: "Enterobacterales",
    aliases: ["klebsiella", "k pneumoniae", "k oxytoca"],
    summary: "Klebsiella is intrinsically ampicillin resistant; ESBL and CRE phenotypes must be recognized separately.",
    keyCaveats: ["Ampicillin does not cover Klebsiella.", "Oral fosfomycin is less reliable for Klebsiella because fosA is common."],
    antibiotics: {
      Ceftriaxone: p("If susceptible and no ESBL/CRE concern."),
      Cefepime: a(),
      "Pip-tazo": a(),
      Ertapenem: a(),
      Meropenem: a(),
      Aztreonam: a(),
      "Amox-clav": v(),
      "Amp-sulbactam": v(),
      Ciprofloxacin: v(),
      Levofloxacin: v(),
      "TMP-SMX": v(),
      "Gent/Tobra": v(),
      Amikacin: v(),
      Nitrofurantoin: site("Cystitis only if susceptible."),
      "Fosfomycin PO": avoid("Not reliable for Klebsiella cystitis because fosA is common."),
      Ampicillin: r("Intrinsic resistance."),
    },
  },
  {
    organism: "ESBL-producing Enterobacterales",
    category: "Enterobacterales",
    aliases: ["esbl", "ctx-m", "ceftriaxone resistant e coli", "ceftriaxone resistant klebsiella"],
    summary: "ESBLs inactivate most penicillins, cephalosporins, and aztreonam; carbapenems are preferred for invasive infection.",
    keyCaveats: ["Piperacillin-tazobactam and cefepime may test susceptible but are not preferred for invasive ESBL infection.", "UTI-only agents do not treat pyelonephritis or bacteremia."],
    antibiotics: {
      Ertapenem: p("Preferred for many non-critically ill invasive ESBL infections."),
      Meropenem: p("Preferred for critical illness, hypoalbuminemia, CNS infection, or Pseudomonas concern."),
      Ciprofloxacin: a("Use only if susceptible and appropriate site."),
      Levofloxacin: a("Use only if susceptible and appropriate site."),
      "TMP-SMX": a("Use only if susceptible and appropriate site."),
      "Gent/Tobra": v(),
      Amikacin: v(),
      Nitrofurantoin: site("Uncomplicated cystitis only."),
      "Fosfomycin PO": site("Uncomplicated E. coli cystitis only; not pyelo/bacteremia."),
      "Pip-tazo": avoid("Not preferred for invasive ESBL infection even if reported susceptible."),
      Cefepime: avoid("Not preferred for ESBL infection outside select low-risk urinary scenarios."),
      Ceftriaxone: r(),
      Aztreonam: r(),
    },
  },
  {
    organism: "AmpC-risk Enterobacterales",
    category: "Enterobacterales",
    aliases: ["ampc", "enterobacter", "klebsiella aerogenes", "citrobacter freundii", "serratia", "morganella", "providencia", "hafnia"],
    summary: "Enterobacter cloacae complex, K. aerogenes, C. freundii, and related organisms can derepress AmpC during therapy.",
    keyCaveats: ["Ceftriaxone may appear active initially but can fail in invasive disease through AmpC derepression.", "Cefepime is often preferred when susceptible."],
    antibiotics: {
      Cefepime: p("Preferred beta-lactam when susceptible for many invasive AmpC-risk infections."),
      Meropenem: a("Use for severe illness, high MICs, or ESBL co-production concern."),
      Ertapenem: a("Active if no Pseudomonas/Acinetobacter concern."),
      Ciprofloxacin: v(),
      Levofloxacin: v(),
      "TMP-SMX": v(),
      "Gent/Tobra": v(),
      Amikacin: v(),
      "Pip-tazo": v("May be suboptimal for invasive infections caused by moderate-risk AmpC organisms."),
      Ceftriaxone: avoid("Avoid for invasive infection because of inducible AmpC risk."),
      Ceftazidime: avoid("Avoid for invasive infection because of inducible AmpC risk."),
      "Amox-clav": r(),
      "Amp-sulbactam": r(),
      Ampicillin: r(),
    },
  },
  {
    organism: "CRE / KPC-producing Enterobacterales",
    category: "Enterobacterales",
    aliases: ["cre", "kpc", "carbapenem resistant enterobacterales"],
    summary: "CRE therapy depends on carbapenemase mechanism; KPC producers are often treated with newer beta-lactam/beta-lactamase inhibitors.",
    keyCaveats: ["Do not treat CRE from a matrix alone; identify carbapenemase when possible.", "Use AST and ID consultation."],
    antibiotics: {
      "Ceftaz-avibactam": p("Preferred for many KPC-producing CRE when susceptible."),
      Cefiderocol: a("Active against many CRE; role depends on mechanism/site."),
      "Tigecycline/Eravacycline": a("Not for bacteremia or UTI as monotherapy."),
      Amikacin: v(),
      "Gent/Tobra": v(),
      Ciprofloxacin: v(),
      Levofloxacin: v(),
      "TMP-SMX": v(),
      Meropenem: avoid("Usually unreliable for CRE unless specific susceptible/non-carbapenemase scenario."),
      Ertapenem: r(),
      Ceftriaxone: r(),
      Cefepime: r(),
      "Pip-tazo": r(),
    },
  },
  {
    organism: "NDM / metallo-beta-lactamase Enterobacterales",
    category: "Enterobacterales",
    aliases: ["ndm", "mbl", "metallo beta lactamase", "vim", "imp"],
    summary: "Metallo-beta-lactamases hydrolyze most beta-lactams but do not hydrolyze aztreonam; avibactam protects aztreonam from co-produced serine beta-lactamases.",
    keyCaveats: ["Aztreonam alone is often insufficient because other beta-lactamases are co-produced.", "Use mechanism-guided therapy and AST."],
    antibiotics: {
      "Ceftaz-avibactam": a("Used with aztreonam when aztreonam-avibactam unavailable."),
      Aztreonam: v("Requires protection from co-produced serine beta-lactamases; often paired with ceftaz-avibactam."),
      Cefiderocol: a("Potential option depending on susceptibility and syndrome."),
      Amikacin: v(),
      "Tigecycline/Eravacycline": a("Not for bacteremia or UTI as monotherapy."),
      Meropenem: r(),
      Ertapenem: r(),
      Cefepime: r(),
    },
  },
  {
    organism: "Pseudomonas aeruginosa",
    category: "Non-fermenters",
    aliases: ["pseudomonas", "psa", "p aeruginosa"],
    summary: "Pseudomonas requires antipseudomonal agents; ertapenem, ceftriaxone, and oral beta-lactams do not cover it.",
    keyCaveats: ["Susceptibility is essential.", "Ceftazidime lacks gram-positive activity; aztreonam lacks gram-positive/anaerobe coverage."],
    antibiotics: {
      "Pip-tazo": p(),
      Ceftazidime: p(),
      Cefepime: p(),
      Meropenem: p(),
      Aztreonam: a(),
      Ciprofloxacin: v(),
      Levofloxacin: v(),
      "Gent/Tobra": v(),
      Amikacin: v(),
      "Ceftaz-avibactam": a("Reserve for resistant isolates when susceptible."),
      "Ceftolo-tazo": a("Reserve for resistant isolates when susceptible."),
      Cefiderocol: a("Reserve for resistant isolates when susceptible."),
      Ertapenem: r("No Pseudomonas activity."),
      Ceftriaxone: r(),
      "TMP-SMX": r(),
      Doxycycline: r(),
    },
  },
  {
    organism: "DTR Pseudomonas aeruginosa",
    category: "Non-fermenters",
    aliases: ["dtr pseudomonas", "mdr pseudomonas", "dtr psa"],
    summary: "Difficult-to-treat resistant Pseudomonas requires susceptibility-guided newer agents.",
    keyCaveats: ["Use AST and local resistance mechanisms.", "Combination therapy decisions depend on syndrome and available active agents."],
    antibiotics: {
      "Ceftolo-tazo": p("Often preferred when susceptible, especially for pneumonia."),
      "Ceftaz-avibactam": a("Option when susceptible."),
      Cefiderocol: a("Option when susceptible."),
      Amikacin: v(),
      "Gent/Tobra": v(),
      Ciprofloxacin: v(),
      Levofloxacin: v(),
      "Pip-tazo": r(),
      Cefepime: r(),
      Meropenem: r(),
    },
  },
  {
    organism: "Acinetobacter baumannii / CRAB",
    category: "Non-fermenters",
    aliases: ["acinetobacter", "crab", "a baumannii"],
    summary: "Acinetobacter susceptibility is unpredictable; carbapenem-resistant A. baumannii is a distinct high-risk phenotype.",
    keyCaveats: ["Ampicillin-sulbactam activity reflects sulbactam, not ampicillin.", "CRAB often requires specialist input and newer agents when available."],
    antibiotics: {
      "Amp-sulbactam": v("May be useful for susceptible A. baumannii; sulbactam is the active component."),
      Meropenem: v("Only if susceptible; often resistant in CRAB."),
      Cefiderocol: a("Potential option for resistant isolates; interpret by syndrome and guidance."),
      "Tigecycline/Eravacycline": a("Not for bacteremia as monotherapy."),
      Minocycline: v(),
      Amikacin: v(),
      "Gent/Tobra": v(),
      "Pip-tazo": v(),
      Cefepime: v(),
    },
  },
  {
    organism: "Stenotrophomonas maltophilia",
    category: "Non-fermenters",
    aliases: ["steno", "s maltophilia"],
    summary: "Stenotrophomonas is intrinsically resistant to carbapenems and many broad gram-negative agents.",
    keyCaveats: ["Distinguish colonization from infection.", "Treatment is susceptibility-guided; invasive disease guidance is evolving."],
    antibiotics: {
      "TMP-SMX": p("Traditional preferred agent when susceptible."),
      Minocycline: a("Common alternative when susceptible."),
      Levofloxacin: v("Resistance can emerge."),
      Cefiderocol: a("Increasingly important option for invasive infection when susceptible."),
      "Ceftaz-avibactam": a("With aztreonam may be an option in selected resistant infections."),
      Aztreonam: v("Often considered with avibactam protection, not alone."),
      Meropenem: r("Intrinsic resistance."),
      Cefepime: r(),
      "Pip-tazo": r(),
    },
  },
  {
    organism: "Haemophilus influenzae",
    category: "Respiratory / GN diplococci",
    aliases: ["h flu", "haemophilus"],
    summary: "Beta-lactamase production is common enough that ampicillin is not reliable empirically.",
    keyCaveats: ["Use syndrome-specific therapy; meningitis differs from otitis/sinusitis/COPD exacerbation."],
    antibiotics: {
      "Amox-clav": p(),
      "Amp-sulbactam": p(),
      Ceftriaxone: p(),
      Cefepime: a(),
      Azithromycin: a(),
      Doxycycline: a(),
      Levofloxacin: a(),
      Ciprofloxacin: a(),
      "TMP-SMX": v(),
      Ampicillin: v("Only reliable if beta-lactamase negative and susceptible."),
    },
  },
  {
    organism: "Neisseria meningitidis",
    category: "Respiratory / GN diplococci",
    aliases: ["meningococcus", "n meningitidis"],
    summary: "Ceftriaxone is standard empiric/definitive therapy for invasive meningococcal disease.",
    keyCaveats: ["Ciprofloxacin, ceftriaxone, or rifampin are used for prophylaxis depending local guidance; rifampin is not in this matrix."],
    antibiotics: {
      Ceftriaxone: p(),
      "Penicillin G": a("If penicillin susceptible."),
      Meropenem: a(),
      Ciprofloxacin: a("Useful for prophylaxis in selected settings, not primary severe disease therapy."),
      Azithromycin: v("Not standard treatment."),
    },
  },
  {
    organism: "Bacteroides fragilis group",
    category: "Anaerobes",
    aliases: ["bacteroides", "b fragilis", "anaerobes"],
    summary: "B. fragilis group requires anaerobe-active therapy; many cephalosporins and fluoroquinolones are unreliable.",
    keyCaveats: ["Ceftriaxone requires metronidazole for intra-abdominal anaerobic coverage.", "Clindamycin resistance is common."],
    antibiotics: {
      "Amox-clav": p(),
      "Amp-sulbactam": p(),
      "Pip-tazo": p(),
      Ertapenem: p(),
      Meropenem: p(),
      Metronidazole: p(),
      "Tigecycline/Eravacycline": a(),
      Clindamycin: avoid("Resistance is common; not reliable for B. fragilis group."),
      Ceftriaxone: r("No reliable anaerobic coverage without metronidazole."),
      Cefepime: r("No reliable anaerobic coverage without metronidazole."),
      Ceftazidime: r(),
      Aztreonam: r(),
    },
  },
  {
    organism: "Oral anaerobes / Fusobacterium",
    category: "Anaerobes",
    aliases: ["oral anaerobes", "fusobacterium", "aspiration anaerobes"],
    summary: "Oral anaerobes are covered by beta-lactam/beta-lactamase inhibitors, carbapenems, and metronidazole-containing combinations.",
    keyCaveats: ["Metronidazole has no aerobic streptococcal coverage, so pair it when mixed oral flora are suspected."],
    antibiotics: {
      "Penicillin G": v("Some oral anaerobes susceptible; beta-lactamase production varies."),
      "Amox-clav": p(),
      "Amp-sulbactam": p(),
      "Pip-tazo": p(),
      Ertapenem: p(),
      Meropenem: p(),
      Metronidazole: a("Add aerobic streptococcal coverage for mixed oral flora."),
      Clindamycin: v("Resistance varies; no gram-negative aerobic coverage."),
    },
  },
  {
    organism: "Clostridioides difficile",
    category: "Anaerobes",
    aliases: ["c diff", "c difficile", "clostridioides difficile", "clostridium difficile"],
    summary: "CDI treatment uses enteral lumen-active agents; systemic susceptibility tables are the wrong frame.",
    keyCaveats: ["Oral vancomycin and fidaxomicin are not systemic antibiotics.", "Metronidazole is no longer preferred for most adult CDI."],
    antibiotics: {
      Fidaxomicin: p("Preferred for initial and recurrent CDI when feasible."),
      "Vancomycin PO": a("Acceptable alternative; required backbone for fulminant CDI."),
      Metronidazole: v("Alternative only in selected nonsevere situations when preferred agents unavailable; IV adjunct in fulminant CDI."),
      "Vancomycin IV": r("IV vancomycin does not treat luminal CDI."),
      Ceftriaxone: r(),
      Cefepime: r(),
      Meropenem: r(),
    },
  },
  {
    organism: "Legionella pneumophila",
    category: "Atypical / intracellular",
    aliases: ["legionella"],
    summary: "Legionella requires intracellular-active therapy; beta-lactams do not work clinically.",
    keyCaveats: ["Use azithromycin or a respiratory fluoroquinolone for pneumonia."],
    antibiotics: {
      Azithromycin: p(),
      Levofloxacin: p(),
      Ciprofloxacin: a(),
      Doxycycline: a(),
      Ceftriaxone: r("Beta-lactams do not treat Legionella."),
      Cefepime: r(),
      "Pip-tazo": r(),
      Meropenem: r(),
    },
  },
  {
    organism: "Mycoplasma / Chlamydophila pneumoniae",
    category: "Atypical / intracellular",
    aliases: ["mycoplasma", "chlamydophila", "atypical pneumonia", "walking pneumonia"],
    summary: "Atypical respiratory pathogens lack classic beta-lactam targets or require intracellular-active agents.",
    keyCaveats: ["Beta-lactams do not cover Mycoplasma."],
    antibiotics: {
      Azithromycin: p(),
      Doxycycline: p(),
      Levofloxacin: a(),
      Ciprofloxacin: a(),
      Ceftriaxone: r(),
      Cefepime: r(),
      "Pip-tazo": r(),
      Meropenem: r(),
      "Vancomycin IV": r(),
    },
  },
  {
    organism: "Rickettsiae / Coxiella burnetii",
    category: "Atypical / intracellular",
    aliases: ["rickettsia", "rmsf", "typhus", "coxiella", "q fever"],
    summary: "Doxycycline is the key empiric therapy for rickettsial disease and Q fever.",
    keyCaveats: ["Do not delay doxycycline for suspected RMSF."],
    antibiotics: {
      Doxycycline: p(),
      Azithromycin: v("Alternative only in selected scenarios."),
      Levofloxacin: v(),
      Ceftriaxone: r(),
      Cefepime: r(),
      "Pip-tazo": r(),
      Meropenem: r(),
      "Vancomycin IV": r(),
    },
  },
  {
    organism: "Pasteurella multocida",
    category: "GI / water / zoonotic",
    aliases: ["pasteurella", "cat bite", "dog bite"],
    summary: "Pasteurella is a key cat/dog bite pathogen; dicloxacillin, cephalexin, and clindamycin alone are unreliable.",
    keyCaveats: ["Bite wounds require polymicrobial coverage, not just Pasteurella coverage."],
    antibiotics: {
      "Amox-clav": p("Preferred oral bite-wound agent."),
      "Amp-sulbactam": p("Preferred IV bite-wound agent."),
      "Pip-tazo": a(),
      Ceftriaxone: a("Pair with anaerobic coverage for bite wounds."),
      Doxycycline: a(),
      Ciprofloxacin: a("Pair with anaerobic coverage for bite wounds."),
      Levofloxacin: a("Pair with anaerobic coverage for bite wounds."),
      Cephalexin: avoid("Unreliable for Pasteurella."),
      Clindamycin: r("No Pasteurella coverage."),
      "Nafcillin/Oxacillin": r(),
    },
  },
  {
    organism: "Vibrio vulnificus / Aeromonas",
    category: "GI / water / zoonotic",
    aliases: ["vibrio", "v vulnificus", "aeromonas", "water exposure"],
    summary: "Water-associated gram-negative wound infections require exposure-specific coverage.",
    keyCaveats: ["Vibrio vulnificus severe infection classically uses doxycycline plus a third-generation cephalosporin or fluoroquinolone-based therapy."],
    antibiotics: {
      Doxycycline: p("Part of classic Vibrio vulnificus combination therapy."),
      Ceftriaxone: a("Often paired with doxycycline for Vibrio vulnificus."),
      Ceftazidime: a("Often paired with doxycycline for Vibrio vulnificus."),
      Ciprofloxacin: a(),
      Levofloxacin: a(),
      Cefepime: a(),
      "TMP-SMX": v(),
      "Amox-clav": avoid("Unreliable for Aeromonas and severe water-associated infections."),
      Cephalexin: r(),
    },
  },
];

export const ORGANISM_CATEGORIES = [
  "All",
  ...Array.from(new Set(ORGANISMS.map((organism) => organism.category))),
] as const;

export function getCell(organism: OrganismSpectrum, antibiotic: AntibioticName): SpectrumCell {
  return organism.antibiotics[antibiotic] ?? DEFAULT_CELL;
}

export function matchesText(value: string, query: string) {
  return value.toLowerCase().includes(query.toLowerCase());
}
