// lib/mechid/data.ts
export type SIR = "Susceptible" | "Intermediate" | "Resistant";
export type MaybeSIR = SIR | null;

export type GroupKey =
  | "Gram-negatives"
  | "Staphylococci"
  | "Enterococcus"
  | "Streptococcus"
  | "Anaerobes";

export const GROUPS: GroupKey[] = [
  "Gram-negatives",
  "Staphylococci",
  "Enterococcus",
  "Streptococcus",
  "Anaerobes",
];

export const GNR_CANON = [
  "Achromobacter xylosoxidans",
  "Acinetobacter baumannii complex",
  "Citrobacter freundii complex",
  "Citrobacter koseri",
  "Enterobacter cloacae complex",
  "Escherichia coli",
  "Klebsiella aerogenes",
  "Klebsiella oxytoca",
  "Klebsiella pneumoniae",
  "Morganella morganii",
  "Proteus mirabilis",
  "Proteus vulgaris group",
  "Pseudomonas aeruginosa",
  "Salmonella enterica",
  "Serratia marcescens",
  "Stenotrophomonas maltophilia",
] as const;

export type GnrOrganism = (typeof GNR_CANON)[number];

export const PANEL: Record<GnrOrganism, string[]> = {
  "Escherichia coli": [
    "Ampicillin",
    "Ampicillin/Sulbactam",
    "Piperacillin/Tazobactam",
    "Cefazolin",
    "Cefoxitin",
    "Ceftriaxone",
    "Ceftazidime",
    "Cefepime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Ertapenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Nitrofurantoin",
    "Trimethoprim/Sulfamethoxazole",
  ],
  "Klebsiella pneumoniae": [
    "Ampicillin/Sulbactam",
    "Piperacillin/Tazobactam",
    "Cefazolin",
    "Cefoxitin",
    "Ceftriaxone",
    "Ceftazidime",
    "Cefepime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Ertapenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Nitrofurantoin",
    "Trimethoprim/Sulfamethoxazole",
  ],
  "Klebsiella oxytoca": [
    "Ampicillin/Sulbactam",
    "Piperacillin/Tazobactam",
    "Cefazolin",
    "Cefoxitin",
    "Ceftriaxone",
    "Ceftazidime",
    "Cefepime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Ertapenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Nitrofurantoin",
    "Trimethoprim/Sulfamethoxazole",
  ],
  "Klebsiella aerogenes": [
    "Ampicillin/Sulbactam",
    "Piperacillin/Tazobactam",
    "Cefoxitin",
    "Ceftriaxone",
    "Ceftazidime",
    "Cefepime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Ertapenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Trimethoprim/Sulfamethoxazole",
  ],
  "Enterobacter cloacae complex": [
    "Ampicillin/Sulbactam",
    "Piperacillin/Tazobactam",
    "Cefoxitin",
    "Ceftriaxone",
    "Ceftazidime",
    "Cefepime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Ertapenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Trimethoprim/Sulfamethoxazole",
  ],
  "Citrobacter freundii complex": [
    "Ampicillin/Sulbactam",
    "Piperacillin/Tazobactam",
    "Cefoxitin",
    "Cefotetan",
    "Ceftriaxone",
    "Ceftazidime",
    "Cefepime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Ertapenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Trimethoprim/Sulfamethoxazole",
  ],
  "Citrobacter koseri": [
    "Ampicillin/Sulbactam",
    "Piperacillin/Tazobactam",
    "Cefazolin",
    "Cefoxitin",
    "Ceftriaxone",
    "Ceftazidime",
    "Cefepime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Ertapenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Nitrofurantoin",
    "Trimethoprim/Sulfamethoxazole",
  ],
  "Serratia marcescens": [
    "Ampicillin/Sulbactam",
    "Piperacillin/Tazobactam",
    "Cefoxitin",
    "Ceftriaxone",
    "Ceftazidime",
    "Cefepime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Ertapenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Trimethoprim/Sulfamethoxazole",
  ],
  "Salmonella enterica": ["Ceftriaxone", "Ciprofloxacin", "Trimethoprim/Sulfamethoxazole"],
  "Proteus mirabilis": [
    "Ampicillin",
    "Ampicillin/Sulbactam",
    "Piperacillin/Tazobactam",
    "Cefazolin",
    "Cefoxitin",
    "Ceftriaxone",
    "Ceftazidime",
    "Cefepime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Ertapenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Trimethoprim/Sulfamethoxazole",
  ],
  "Proteus vulgaris group": [
    "Ampicillin/Sulbactam",
    "Piperacillin/Tazobactam",
    "Cefoxitin",
    "Ceftriaxone",
    "Ceftazidime",
    "Cefepime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Ertapenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Trimethoprim/Sulfamethoxazole",
  ],
  "Morganella morganii": [
    "Ampicillin/Sulbactam",
    "Piperacillin/Tazobactam",
    "Cefoxitin",
    "Ceftriaxone",
    "Ceftazidime",
    "Cefepime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Ertapenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Trimethoprim/Sulfamethoxazole",
  ],
  "Acinetobacter baumannii complex": [
    "Ampicillin/Sulbactam",
    "Piperacillin/Tazobactam",
    "Ceftriaxone",
    "Cefepime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Trimethoprim/Sulfamethoxazole",
  ],
  "Achromobacter xylosoxidans": [
    "Piperacillin/Tazobactam",
    "Cefepime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Trimethoprim/Sulfamethoxazole",
  ],
  "Pseudomonas aeruginosa": [
    "Piperacillin/Tazobactam",
    "Cefepime",
    "Ceftazidime",
    "Aztreonam",
    "Imipenem",
    "Meropenem",
    "Gentamicin",
    "Tobramycin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
  ],
  "Stenotrophomonas maltophilia": ["Trimethoprim/Sulfamethoxazole", "Levofloxacin"],
};

export type CascadeRule =
  | { target: string; rule: "same_as"; ref: string }
  | { target: string; rule: "sus_if_sus"; ref: string }
  | { target: string; rule: "sus_if_any_sus"; refs: string[] }
  | { target: string; rule: "sus_if_sus_else_res"; ref: string }
  | { target: string; rule: "same_as_else_sus_if_sus"; primary: string; fallback: string };

export type OrganismRules = {
  intrinsic_resistance: string[];
  cascade: CascadeRule[];
};

export const RULES: Partial<Record<GnrOrganism, OrganismRules>> = {
  "Escherichia coli": {
    intrinsic_resistance: [],
    cascade: [
      { target: "Ceftriaxone", rule: "same_as", ref: "Cefotaxime" },
      { target: "Cefepime", rule: "sus_if_any_sus", refs: ["Ceftriaxone", "Cefotaxime", "Cefazolin"] },
      { target: "Cefuroxime", rule: "sus_if_sus", ref: "Cefazolin" },
      { target: "Cefoxitin", rule: "sus_if_sus", ref: "Cefazolin" },
      { target: "Cefotetan", rule: "sus_if_sus", ref: "Cefazolin" },
      { target: "Cefpodoxime", rule: "same_as_else_sus_if_sus", primary: "Ceftriaxone", fallback: "Cefazolin" },
      { target: "Doxycycline", rule: "sus_if_sus_else_res", ref: "Tetracycline" },
    ],
  },
  "Klebsiella pneumoniae": { intrinsic_resistance: ["Ampicillin"], cascade: [] },
  "Klebsiella oxytoca": { intrinsic_resistance: ["Ampicillin"], cascade: [] },
  "Klebsiella aerogenes": {
    intrinsic_resistance: ["Ampicillin", "Cefazolin"],
    cascade: [{ target: "Cefepime", rule: "sus_if_any_sus", refs: ["Ceftriaxone"] }],
  },
  "Enterobacter cloacae complex": {
    intrinsic_resistance: ["Ampicillin", "Cefazolin"],
    cascade: [{ target: "Cefepime", rule: "sus_if_any_sus", refs: ["Ceftriaxone"] }],
  },
  "Citrobacter freundii complex": {
    intrinsic_resistance: ["Ampicillin", "Cefazolin", "Cefoxitin", "Cefotetan"],
    cascade: [
      { target: "Cefepime", rule: "sus_if_any_sus", refs: ["Ceftriaxone", "Cefotaxime"] },
      { target: "Ceftazidime", rule: "sus_if_any_sus", refs: ["Ceftriaxone", "Cefotaxime"] },
    ],
  },
  "Citrobacter koseri": {
    intrinsic_resistance: [],
    cascade: [
      { target: "Cefepime", rule: "sus_if_any_sus", refs: ["Ceftriaxone", "Cefotaxime", "Cefazolin"] },
      { target: "Ceftazidime", rule: "sus_if_any_sus", refs: ["Ceftriaxone", "Cefotaxime", "Cefazolin"] },
    ],
  },
  "Serratia marcescens": { intrinsic_resistance: ["Ampicillin", "Cefazolin", "Tetracycline"], cascade: [] },
  "Proteus mirabilis": { intrinsic_resistance: ["Nitrofurantoin"], cascade: [] },
  "Proteus vulgaris group": { intrinsic_resistance: ["Nitrofurantoin", "Tetracycline", "Tigecycline", "Colistin"], cascade: [] },
  "Morganella morganii": { intrinsic_resistance: ["Nitrofurantoin"], cascade: [] },
  "Pseudomonas aeruginosa": {
    intrinsic_resistance: ["Ampicillin", "Cefazolin", "Ceftriaxone", "Ertapenem", "Tetracycline", "Tigecycline"],
    cascade: [],
  },
  "Salmonella enterica": { intrinsic_resistance: [], cascade: [] },
  "Stenotrophomonas maltophilia": { intrinsic_resistance: [], cascade: [] },
};

export const SIR_CHOICES: ("" | SIR)[] = ["", "Susceptible", "Intermediate", "Resistant"];
